/*Users List URL */
const USERS_URL = "https://6172cfe5110a740017222e2b.mockapi.io/elements"

/* Actions */
const ADD_TASK = "ADD_TASK"
const GET_USERS_LIST = "GET_USERS_LIST"
const GET_USERS_LIST_LOADING = "GET_USERS_LIST_LOADING"

export { USERS_URL, ADD_TASK, GET_USERS_LIST, GET_USERS_LIST_LOADING }